# Generated by Django 4.2.6 on 2023-10-16 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_proveidor'),
    ]

    operations = [
        migrations.AddField(
            model_name='producte',
            name='proveidor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productes', to='api.proveidor', verbose_name='Proveidor'),
            preserve_default=False,
        ),
    ]
