# Generated by Django 4.2.6 on 2023-10-16 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0003_producte_proveidor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuari',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('dni', models.CharField(blank=True, max_length=20, null=True, verbose_name='DNI')),
                ('bio', models.CharField(blank=True, max_length=250, null=True, verbose_name='Bio')),
                ('dataNaixement', models.DateField(blank=True, null=True, verbose_name='Data naixement')),
                ('telefon', models.IntegerField(blank=True, null=True, verbose_name='Telefon')),
                ('imatge', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imatge')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('usuari', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.usuari', verbose_name='Usuari')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('usuari', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.usuari', verbose_name='Usuari')),
            ],
        ),
        migrations.CreateModel(
            name='Treballador',
            fields=[
                ('usuari', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.usuari', verbose_name='Usuari')),
            ],
        ),
    ]
