# Generated by Django 4.2.6 on 2023-11-12 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_compra'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'verbose_name_plural': 'Compres'},
        ),
        migrations.CreateModel(
            name='LiniaCompra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador')),
                ('quantitat', models.IntegerField(default=1, verbose_name='Quantitat')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liniesCompra', to='api.compra', verbose_name='Compra')),
                ('producte', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='liniesCompra', to='api.producte', verbose_name='Producte')),
            ],
            options={
                'verbose_name_plural': 'Línies Compra',
            },
        ),
    ]
