# Generated by Django 4.2.6 on 2023-11-13 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_compra_options_liniacompra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Esdeveniment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('descripcio', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Descripció')),
                ('dataCreacio', models.DateTimeField(auto_now_add=True, verbose_name='Data creació')),
                ('data', models.DateTimeField(blank=True, null=True, verbose_name='Data')),
                ('aforament', models.IntegerField(blank=True, default=0, null=True, verbose_name='Aforament')),
                ('durada', models.CharField(blank=True, max_length=100, null=True, verbose_name='Durada')),
                ('ubicacio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicació')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='esdeveniments', to='api.admin', verbose_name='Creador')),
                ('participants', models.ManyToManyField(related_name='esdeveniments', to='api.client', verbose_name='Participants')),
            ],
        ),
    ]
