# Generated by Django 4.2.6 on 2023-11-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_esdeveniment_data_alter_usuari_datanaixement'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='punts',
            field=models.IntegerField(default=0, verbose_name='Punts client'),
        ),
    ]
