# Generated by Django 4.2.6 on 2023-12-03 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_compra_descompte_compra_dinerscanvi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('descripcio', models.CharField(max_length=100, verbose_name='Descripció')),
                ('descompte', models.FloatField(blank=True, null=True, verbose_name='Descompte')),
                ('dataInici', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data inici')),
                ('dataFinal', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data final')),
            ],
        ),
        migrations.CreateModel(
            name='CuponsClients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador')),
                ('quantitat', models.IntegerField(default=1, verbose_name='Quantitat')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupons', to='api.client', verbose_name='Client')),
                ('cupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='api.cupo', verbose_name='Cupó')),
            ],
            options={
                'unique_together': {('client', 'cupo')},
            },
        ),
    ]
