# Generated by Django 4.2.6 on 2023-12-03 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_cupo_cuponsclients'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cupo',
            options={'verbose_name_plural': 'Cupons'},
        ),
    ]
