# Generated by Django 4.2.6 on 2023-12-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_cupo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupo',
            name='punts',
            field=models.IntegerField(default=1, verbose_name='Punts necessaris'),
        ),
    ]
