# Generated by Django 4.2.6 on 2023-12-12 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_cupo_punts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compres', to='api.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='treballador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compres', to='api.treballador', verbose_name='Treballador'),
        ),
        migrations.AlterField(
            model_name='esdeveniment',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esdeveniments', to='api.admin', verbose_name='Creador'),
        ),
        migrations.AlterField(
            model_name='liniacompra',
            name='producte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liniesCompra', to='api.producte', verbose_name='Producte'),
        ),
    ]
